### ISSUE TITLE
Initial Release TODO

### ISSUE THREAD

**Issue by gary-kim** [gary-kim/scraper-dashboard#2]
- [ ] Make open source (#1)
- [ ] Do hash checking on server
- [ ] Documentation for how to set up server
- [ ] API versioning for server
- [ ] Configurable update time
    - [ ] Separate intervals for each
- [ ] Don't request every permission
- [ ] Way to store logins?
- [ ] Show favicons on cards?
- [ ] Wayback machine integration?
- [ ] Capture locally without external server?
    - Not sure if this is possible if the tab is not opened.
- [ ] Set up dependency updates?
